# ============================================================================
# KEY VAULT MODULE VARIABLES
# ============================================================================

# Key Vault name (must be globally unique across all Azure)
variable "key_vault_name" {
  description = "Name of the Azure Key Vault instance (3-24 chars, globally unique)"
  type        = string

  # Validation: Enforce Azure Key Vault naming requirements
  validation {
    condition     = length(var.key_vault_name) >= 3 && length(var.key_vault_name) <= 24
    error_message = "Key Vault name must be 3-24 characters long"
  }

  validation {
    condition     = can(regex("^[a-zA-Z0-9-]+$", var.key_vault_name))
    error_message = "Key Vault name can only contain alphanumeric characters and hyphens"
  }
}

# Azure region for Key Vault deployment
variable "location" {
  description = "Azure region for Key Vault (e.g., southcentralus)"
  type        = string
}

# Resource group name for Key Vault
variable "resource_group_name" {
  description = "Name of the resource group to deploy Key Vault into"
  type        = string
}

# Subnet ID for network ACL restriction
variable "subnet_id" {
  description = "Subnet ID to allow Key Vault access from (VM subnet)"
  type        = string
}

# RCON password value to store as secret
variable "rcon_password" {
  description = "RCON password for Minecraft server (generated by random_password)"
  type        = string
  sensitive   = true # Prevents Terraform from displaying value in logs/output
}

# Tags for resource governance
variable "tags" {
  description = "Tags to apply to Key Vault resources (environment, app, owner, etc.)"
  type        = map(string)
  default     = {}
}

# Admin source IP for Key Vault firewall access
variable "admin_source_ip" {
  description = "Public IP address allowed for Key Vault management (CIDR notation)"
  type        = string
}

